-- question definition
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a female ?', 10);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character have long hair ?', 2);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character short ?', 3);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a main protagonist ?', 8);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a student ?', 5);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character have super powers ?', 7);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character super smart ?', 8);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character exist in real life ?', 10);

INSERT INTO "Question" VALUES (DEFAULT, 'is your character created artificially ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character from an anime ?', 5);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character always wear a T-Shirt ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a male ?', 5);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character''s hair color black ?', 10);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character''s hair color orange ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character''s hair color white ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character''s hair color pink ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character''s haircut unusual ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character blonde ?', 6);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character from an american comic ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character know how to sing ?', 8);

INSERT INTO "Question" VALUES (DEFAULT, 'is your character funny ?', 7);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character from a romance show ?', 8);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character from a comedy show ?', 7);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character from Academy City ?', 8);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character more than 1m70 tall ?', 7);

INSERT INTO "Question" VALUES (DEFAULT, 'does your character always wear blue ?', 3);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character always wear black ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a cyborg ?', 4);

INSERT INTO "Question" VALUES (DEFAULT, 'is your character related to Disney ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character related to Marvel ?', 5);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character related to DC Comics ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character related to a Movie ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character always wear a mask ?', 2);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a big brother ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a big sister ?', 6);

INSERT INTO "Question" VALUES (DEFAULT, 'Can your character fly ?', 4);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character run fast ?', 2);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a "super" human ?', 8);
INSERT INTO "Question" VALUES (DEFAULT, 'can your character read people''s minds ?', 9);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character super strong ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a magician ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a sadist ?', 6);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character the main antagonist of the series they''re in ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character sometimes act like an idiot ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character from Youtube ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character stream on Twitch ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character popular on social media ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a streamer ?', 8);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character from a video game ?', 10);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character asian ?', 10);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character black ?', 2);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character into BL ?', 2);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character an introvert ?', 8);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character have a lot of friends ?', 5);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character good at electronics ?', 3);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character born after 2000 ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character time travel ?', 4);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character have Chuunibyou Syndrome ?', 7);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a Tsundere ?', 7);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character shy ?', 2);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character an idol ?', 6);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character play an instrument ?', 7);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character wear glasses ?', 5);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character come from an all girl school ?', 6);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character play violin ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character play piano ?', 5);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character good at computers ?', 5);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a god ?', 5);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character noisy ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character''s eyes unusual ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character from a manga ?', 7);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character play chess ?', 9);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character play shogi ?', 5);

INSERT INTO "Question" VALUES (DEFAULT, 'is your character good at sports ?', 5);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character popular in the series they are in ?', 5);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a vocaloid ?', 4);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character an orphan ?', 2);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character like to tease ?', 2);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character have brown hair ?', 4);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character from a AAA game ?', 5);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a pervert ?', 3);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character come from a band?', 3);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character skinny ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character an animal ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a cat ?', 3);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character big ?', 7);

INSERT INTO "Question" VALUES (DEFAULT, 'is your character''s hair color yellow ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a butler ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a maid ?', 6);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character an elf ?', 5);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a slime ?', 5);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character related to an Isekai anime ?', 5);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character still alive ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a magical creature ?', 3);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a monster ?', 9);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character related to a mythological creature ?', 4);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character from Fate Series ?', 9);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character from Monogatari Series ?', 8);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character wear an armor ?', 6);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character wear an uniform ?', 3);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character have scars ?', 7);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character have tattoos ?', 7);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character have red eyes ?', 8);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character have blue eyes ?', 5);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character have brown eyes ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a cyclope ?', 3);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character wear a suit ?', 9);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a vampire ?', 9);

INSERT INTO "Question" VALUES (DEFAULT, 'is your character''s hair color red ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character from space ?', 1);

INSERT INTO "Question" VALUES (DEFAULT, 'does your character live with a double identity ?', 5);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character mute ?', 2);
INSERT INTO "Question" VALUES (DEFAULT, 'can your character become invisible ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character in a CG movie ?', 3);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character have unusual ears ?', 7);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character related to angels ?', 7);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character always look depressed ?', 2);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character related to demons ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character have piercings ?', 6);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character some sort of leader ?', 6);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a robot ?', 8);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character have a sword ?', 6);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character an epser ?', 9);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a hacker ?', 7);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character like to play video games ?', 3);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character from another world ?', 4);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character wear a hat ?', 9);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a model ?', 9);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character an humanoid ?', 2);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character from the army ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character a martial artist ?', 1);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character rich ?', 7);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character from a poor family ?', 2);
INSERT INTO "Question" VALUES (DEFAULT, 'does your character like girls ?', 6);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character some sort of detective ?', 8);
INSERT INTO "Question" VALUES (DEFAULT, 'is your character related to rocks ?', 3);

-- answer
INSERT INTO "Character" VALUES (DEFAULT, 'Rina Tennoji', NULL, 1, '@me');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_1', 'CHR_1');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_2', 'CHR_1');
INSERT INTO "Answer" VALUES (DEFAULT, 0.8, 'QST_3', 'CHR_1');
INSERT INTO "Answer" VALUES (DEFAULT, 0.5, 'QST_4', 'CHR_1');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_5', 'CHR_1');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_6', 'CHR_1');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_7', 'CHR_1');

INSERT INTO "Character" VALUES (DEFAULT, 'Ai Miyashita', NULL, 1, '@me');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_1', 'CHR_2');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_2', 'CHR_2');
INSERT INTO "Answer" VALUES (DEFAULT, 0.5, 'QST_3', 'CHR_2');
INSERT INTO "Answer" VALUES (DEFAULT, 0.2, 'QST_4', 'CHR_2');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_5', 'CHR_2');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_6', 'CHR_2');
INSERT INTO "Answer" VALUES (DEFAULT, 0.5, 'QST_7', 'CHR_2');

INSERT INTO "Character" VALUES (DEFAULT, 'Kanan Matsuura', NULL, 1, '@me');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_1', 'CHR_3');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_2', 'CHR_3');
INSERT INTO "Answer" VALUES (DEFAULT, 0.5, 'QST_3', 'CHR_3');
INSERT INTO "Answer" VALUES (DEFAULT, 0.2, 'QST_4', 'CHR_3');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_5', 'CHR_3');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_6', 'CHR_3');
INSERT INTO "Answer" VALUES (DEFAULT, 0.7, 'QST_7', 'CHR_3');

INSERT INTO "Character" VALUES (DEFAULT, 'Dia Kurosawa', NULL, 1, '@me');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_1', 'CHR_4');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_2', 'CHR_4');
INSERT INTO "Answer" VALUES (DEFAULT, 0.5, 'QST_3', 'CHR_4');
INSERT INTO "Answer" VALUES (DEFAULT, 0.2, 'QST_4', 'CHR_4');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_5', 'CHR_4');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_6', 'CHR_4');
INSERT INTO "Answer" VALUES (DEFAULT, 0.8, 'QST_7', 'CHR_4');

INSERT INTO "Character" VALUES (DEFAULT, 'Ruby Kurosawa', NULL, 1, '@me');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_1', 'CHR_5');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_2', 'CHR_5');
INSERT INTO "Answer" VALUES (DEFAULT, 0.5, 'QST_3', 'CHR_5');
INSERT INTO "Answer" VALUES (DEFAULT, 0.5, 'QST_4', 'CHR_5');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_5', 'CHR_5');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_6', 'CHR_5');
INSERT INTO "Answer" VALUES (DEFAULT, 0.5, 'QST_7', 'CHR_5');

INSERT INTO "Character" VALUES (DEFAULT, 'Misaka Mikoto', NULL, 1, '@me');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_1', 'CHR_6');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_2', 'CHR_6');
INSERT INTO "Answer" VALUES (DEFAULT, 0.7, 'QST_3', 'CHR_6');
INSERT INTO "Answer" VALUES (DEFAULT, 0.5, 'QST_4', 'CHR_6');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_5', 'CHR_6');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_6', 'CHR_6');
INSERT INTO "Answer" VALUES (DEFAULT, 0.8, 'QST_7', 'CHR_6');

INSERT INTO "Character" VALUES (DEFAULT, 'Kamijou Touma', NULL, 1, '@me');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_1', 'CHR_7');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_2', 'CHR_7');
INSERT INTO "Answer" VALUES (DEFAULT, 0.5, 'QST_3', 'CHR_7');
INSERT INTO "Answer" VALUES (DEFAULT, 0.2, 'QST_4', 'CHR_7');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_5', 'CHR_7');
INSERT INTO "Answer" VALUES (DEFAULT, 0.2, 'QST_6', 'CHR_7');
INSERT INTO "Answer" VALUES (DEFAULT, 0.6, 'QST_7', 'CHR_7');

INSERT INTO "Character" VALUES (DEFAULT, 'Last Order', NULL, 1, '@me');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_1', 'CHR_8');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_2', 'CHR_8');
INSERT INTO "Answer" VALUES (DEFAULT, 0.9, 'QST_3', 'CHR_8');
INSERT INTO "Answer" VALUES (DEFAULT, 0.8, 'QST_4', 'CHR_8');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_5', 'CHR_8');
INSERT INTO "Answer" VALUES (DEFAULT, 0.1, 'QST_6', 'CHR_8');
INSERT INTO "Answer" VALUES (DEFAULT, 0.2, 'QST_7', 'CHR_8');

INSERT INTO "Character" VALUES (DEFAULT, 'Saten Ruiko', NULL, 1, '@me');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_1', 'CHR_9');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_2', 'CHR_9');
INSERT INTO "Answer" VALUES (DEFAULT, 0.7, 'QST_3', 'CHR_9');
INSERT INTO "Answer" VALUES (DEFAULT, 0.2, 'QST_4', 'CHR_9');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_5', 'CHR_9');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_6', 'CHR_9');
INSERT INTO "Answer" VALUES (DEFAULT, 0.4, 'QST_7', 'CHR_9');

INSERT INTO "Character" VALUES (DEFAULT, 'Accelerator', NULL, 1, '@me');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_1', 'CHR_10');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_2', 'CHR_10');
INSERT INTO "Answer" VALUES (DEFAULT, 0.2, 'QST_3', 'CHR_10');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_4', 'CHR_10');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_5', 'CHR_10');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_6', 'CHR_10');
INSERT INTO "Answer" VALUES (DEFAULT, 0.9, 'QST_7', 'CHR_10');

INSERT INTO "Character" VALUES (DEFAULT, 'Keima Katsuragi', NULL, 1, '@me');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_1', 'CHR_11');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_2', 'CHR_11');
INSERT INTO "Answer" VALUES (DEFAULT, 0.7, 'QST_3', 'CHR_11');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_4', 'CHR_11');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_5', 'CHR_11');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_6', 'CHR_11');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_7', 'CHR_11');

INSERT INTO "Character" VALUES (DEFAULT, 'Chihiro Kosaka', NULL, 1, '@me');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_1', 'CHR_12');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_2', 'CHR_12');
INSERT INTO "Answer" VALUES (DEFAULT, 0.7, 'QST_3', 'CHR_12');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_4', 'CHR_12');
INSERT INTO "Answer" VALUES (DEFAULT, 0.8, 'QST_5', 'CHR_12');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_6', 'CHR_12');
INSERT INTO "Answer" VALUES (DEFAULT, 0.2, 'QST_7', 'CHR_12');

INSERT INTO "Character" VALUES (DEFAULT, 'Kana Asumi', NULL, 1, '@me');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_1', 'CHR_13');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_2', 'CHR_13');
INSERT INTO "Answer" VALUES (DEFAULT, 0.7, 'QST_3', 'CHR_13');
INSERT INTO "Answer" VALUES (DEFAULT, 0.1, 'QST_4', 'CHR_13');
INSERT INTO "Answer" VALUES (DEFAULT, 1, 'QST_5', 'CHR_13');
INSERT INTO "Answer" VALUES (DEFAULT, 0, 'QST_6', 'CHR_13');
INSERT INTO "Answer" VALUES (DEFAULT, 0.2, 'QST_7', 'CHR_13');